-- Exported from QuickDBD: https://www.quickdatabasediagrams.com/
-- Link to schema: https://app.quickdatabasediagrams.com/#/d/mgEXL2
-- NOTE! If you have used non-SQL datatypes in your design, you will have to change these here.


CREATE TABLE "2015_income" (
    "CensusTract" FLOAT,
    "State" VARCHAR,
    "County" VARCHAR,
    "lasnaphalf" FLOAT,
    "lasnaphalfshare" FLOAT,
    "lapop1" FLOAT,
    "lapop1share" FLOAT,
    "lalowi1" FLOAT,
    "lalowi1share" FLOAT,
    "lasnap1" FLOAT,
    "lasnap1share" FLOAT,
    "lapop10" FLOAT,
    "lapop10share" FLOAT,
    "lalowi10" FLOAT,
    "lalowi10share" FLOAT,
    "lasnap10" FLOAT,
    "lasnap10share" FLOAT,
    "lasnap20" FLOAT,
    "lasnap20share" FLOAT
);

CREATE TABLE "2015_race" (
    "CensusTract" FLOAT,
    "State" VARCHAR,
    "County" VARCHAR,
    "lawhitehalf" FLOAT,
    "lawhitehalfshare" FLOAT,
    "lablackhalf" FLOAT,
    "lablackhalfshare" FLOAT,
    "laasianhalf" FLOAT,
    "laasianhalfshare" FLOAT,
    "lanhopihalf" FLOAT,
    "lanhopihalfshare" FLOAT,
    "laaianhalf" FLOAT,
    "laaianhalfshare" FLOAT,
    "laomultirhalf" FLOAT,
    "laomultirhalfshare" FLOAT,
    "lahisphalf" FLOAT,
    "lahisphalfshare" FLOAT,
    "lahunvhalf" FLOAT,
    "lahunvhalfshare" FLOAT,
    "lawhite1" FLOAT,
    "lawhite1share" FLOAT,
    "lablack1" FLOAT,
    "lablack1share" FLOAT,
    "laasian1" FLOAT,
    "laasian1share" FLOAT,
    "lanhopi1" FLOAT,
    "lanhopi1share" FLOAT,
    "laaian1" FLOAT,
    "laaian1share" FLOAT,
    "laomultir1" FLOAT,
    "laomultir1share" FLOAT,
    "lahisp1" FLOAT,
    "lahisp1share" FLOAT,
    "lawhite10" FLOAT,
    "lawhite10share" FLOAT,
    "lablack10" FLOAT,
    "lablack10share" FLOAT,
    "laasian10" FLOAT,
    "laasian10share" FLOAT ,
    "lanhopi10" FLOAT,
    "lanhopi10share" FLOAT,
    "laaian10" FLOAT,
    "laaian10share" FLOAT,
    "laomultir10" FLOAT ,
    "laomultir10share" FLOAT,
    "lahisp10" FLOAT,
    "lahisp10share" FLOAT
);

CREATE TABLE "2015_locale" (
    "CensusTract" FLOAT,
    "State" VARCHAR,
    "County" VARCHAR,
    "LAPOP05_10" FLOAT,
    "LAPOP1_20" FLOAT,
    "LALOWI1_10" FLOAT,
    "LALOWI05_10" FLOAT,
    "LALOWI1_20" FLOAT,
    "lapophalf" FLOAT,
    "lapophalfshare" FLOAT,
    "lalowihalf" FLOAT,
    "lalowihalfshare" FLOAT,
    "lakidshalf" FLOAT,
    "lakidshalfshare" FLOAT,
    "laseniorshalf" FLOAT,
    "laseniorshalfshare" FLOAT,
    "lahunvhalf" FLOAT,
    "lahunvhalfshare" FLOAT,
    "lakids1" FLOAT,
    "lakids1share" FLOAT,
    "laseniors1" FLOAT,
    "laseniors1share" FLOAT,
    "lahunv1" FLOAT,
    "lahunv1share" FLOAT,
    "lakids10" FLOAT,
    "lakids10share" FLOAT,
    "laseniors10" FLOAT,
    "laseniors10share" FLOAT,
    "lahunv10" FLOAT,
    "lahunv10share" FLOAT,
    "lapop20" FLOAT,
    "lapop20share" FLOAT,
    "lalowi20" FLOAT,
    "lalowi20share" FLOAT,
    "lakids20" FLOAT,
    "lakids20share" FLOAT,
    "laseniors20" FLOAT,
    "laseniors20share" FLOAT,
    "lahunv20" FLOAT,
    "lahunv20share" FLOAT 
);

CREATE TABLE "2019_income" (
    "CensusTract" FLOAT,
    "State" VARCHAR,
    "County" VARCHAR,
    "lasnaphalf" FLOAT,
    "lasnaphalfshare" FLOAT,
    "lapop1" FLOAT,
    "lapop1share" FLOAT,
    "lalowi1" FLOAT,
    "lalowi1share" FLOAT,
    "lasnap1" FLOAT,
    "lasnap1share" FLOAT,
    "lapop10" FLOAT,
    "lapop10share" FLOAT,
    "lalowi10" FLOAT,
    "lalowi10share" FLOAT,
    "lasnap10" FLOAT,
    "lasnap10share" FLOAT,
    "lasnap20" FLOAT,
    "lasnap20share" FLOAT
);

CREATE TABLE "2019_race" (
    "CensusTract" FLOAT,
    "State" VARCHAR,
    "County" VARCHAR,
    "lawhitehalf" FLOAT,
    "lawhitehalfshare" FLOAT,
    "lablackhalf" FLOAT,
    "lablackhalfshare" FLOAT,
    "laasianhalf" FLOAT,
    "laasianhalfshare" FLOAT,
    "lanhopihalf" FLOAT,
    "lanhopihalfshare" FLOAT,
    "laaianhalf" FLOAT,
    "laaianhalfshare" FLOAT,
    "laomultirhalf" FLOAT,
    "laomultirhalfshare" FLOAT,
    "lahisphalf" FLOAT,
    "lahisphalfshare" FLOAT,
    "lahunvhalf" FLOAT,
    "lahunvhalfshare" FLOAT,
    "lawhite1" FLOAT,
    "lawhite1share" FLOAT,
    "lablack1" FLOAT,
    "lablack1share" FLOAT,
    "laasian1" FLOAT,
    "laasian1share" FLOAT,
    "lanhopi1" FLOAT,
    "lanhopi1share" FLOAT,
    "laaian1" FLOAT,
    "laaian1share" FLOAT,
    "laomultir1" FLOAT,
    "laomultir1share" FLOAT,
    "lahisp1" FLOAT,
    "lahisp1share" FLOAT,
    "lawhite10" FLOAT,
    "lawhite10share" FLOAT,
    "lablack10" FLOAT,
    "lablack10share" FLOAT,
    "laasian10" FLOAT,
    "laasian10share" FLOAT ,
    "lanhopi10" FLOAT,
    "lanhopi10share" FLOAT,
    "laaian10" FLOAT,
    "laaian10share" FLOAT,
    "laomultir10" FLOAT ,
    "laomultir10share" FLOAT,
    "lahisp10" FLOAT,
    "lahisp10share" FLOAT
);

CREATE TABLE "2019_locale" (
"CensusTract" FLOAT,
    "State" VARCHAR,
    "County" VARCHAR,
    "LAPOP05_10" FLOAT,
    "LAPOP1_20" FLOAT,
    "LALOWI1_10" FLOAT,
    "LALOWI05_10" FLOAT,
    "LALOWI1_20" FLOAT,
    "lapophalf" FLOAT,
    "lapophalfshare" FLOAT,
    "lalowihalf" FLOAT,
    "lalowihalfshare" FLOAT,
    "lakidshalf" FLOAT,
    "lakidshalfshare" FLOAT,
    "laseniorshalf" FLOAT,
    "laseniorshalfshare" FLOAT,
    "lahunvhalf" FLOAT,
    "lahunvhalfshare" FLOAT,
    "lakids1" FLOAT,
    "lakids1share" FLOAT,
    "laseniors1" FLOAT,
    "laseniors1share" FLOAT,
    "lahunv1" FLOAT,
    "lahunv1share" FLOAT,
    "lakids10" FLOAT,
    "lakids10share" FLOAT,
    "laseniors10" FLOAT,
    "laseniors10share" FLOAT,
    "lahunv10" FLOAT,
    "lahunv10share" FLOAT,
    "lapop20" FLOAT,
    "lapop20share" FLOAT,
    "lalowi20" FLOAT,
    "lalowi20share" FLOAT,
    "lakids20" FLOAT,
    "lakids20share" FLOAT,
    "laseniors20" FLOAT,
    "laseniors20share" FLOAT,
    "lahunv20" FLOAT,
    "lahunv20share" FLOAT 
);

CREATE TABLE "2015_census" (
    "CensusTract" FLOAT   NOT NULL,
    "State" VARCHAR   NOT NULL,
    "County" VARCHAR   NOT NULL,
    "Urban" BOOL   NOT NULL,
    "POP2010" INT   NOT NULL,
    "OHU2010" INT   NOT NULL,
    "GroupQuartersFlag" BOOL   NOT NULL,
    "NUMGQTRS" INT   NOT NULL,
    "PCTGQTRS" FLOAT   NOT NULL,
    "LILATracts_1And10" BOOL   NOT NULL,
    "LILATracts_halfAnd10" BOOL   NOT NULL,
    "LILATracts_1And20" BOOL   NOT NULL,
    "LILATracts_Vehicle" BOOL   NOT NULL,
    "HUNVFlag" BOOL   NOT NULL,
    "LowIncomeTracts" BOOL   NOT NULL,
    "PovertyRate" FLOAT   NOT NULL,
    "MedianFamilyIncome" INT   NOT NULL,
    "LA1and10" BOOL   NOT NULL,
    "LAhalfand10" BOOL   NOT NULL,
    "LA1and20" BOOL   NOT NULL,
    "LATracts_half" BOOL   NOT NULL,
    "LATracts1" BOOL   NOT NULL,
    "LATracts10" BOOL   NOT NULL,
    "LATracts20" BOOL   NOT NULL,
    "LATractsVehicle_20" BOOL   NOT NULL,
    "LAPOP1_10" FLOAT   NOT NULL,
    "LAPOP05_10" FLOAT   NOT NULL,
    "LAPOP1_20" FLOAT   NOT NULL,
    "LALOWI1_10" FLOAT   NOT NULL,
    "LALOWI05_10" FLOAT   NOT NULL,
    "LALOWI1_20" FLOAT   NOT NULL,
    "lapophalf" FLOAT   NOT NULL,
    "lapophalfshare" FLOAT   NOT NULL,
    "lalowihalf" FLOAT   NOT NULL,
    "lalowihalfshare" FLOAT   NOT NULL,
    "lakidshalf" FLOAT   NOT NULL,
    "lakidshalfshare" FLOAT   NOT NULL,
    "laseniorshalf" FLOAT   NOT NULL,
    "laseniorshalfshare" FLOAT   NOT NULL,
    "lawhitehalf" FLOAT   NOT NULL,
    "lawhitehalfshare" FLOAT   NOT NULL,
    "lablackhalf" FLOAT   NOT NULL,
    "lablackhalfshare" FLOAT   NOT NULL,
    "laasianhalf" FLOAT   NOT NULL,
    "laasianhalfshare" FLOAT   NOT NULL,
    "lanhopihalf" FLOAT   NOT NULL,
    "lanhopihalfshare" FLOAT   NOT NULL,
    "laaianhalf" FLOAT   NOT NULL,
    "laaianhalfshare" FLOAT   NOT NULL,
    "laomultirhalf" FLOAT   NOT NULL,
    "laomultirhalfshare" FLOAT   NOT NULL,
    "lahisphalf" FLOAT   NOT NULL,
    "lahisphalfshare" FLOAT   NOT NULL,
    "lahunvhalf" FLOAT   NOT NULL,
    "lahunvhalfshare" FLOAT   NOT NULL,
    "lasnaphalf" FLOAT   NOT NULL,
    "lasnaphalfshare" FLOAT   NOT NULL,
    "lapop1" FLOAT   NOT NULL,
    "lapop1share" FLOAT   NOT NULL,
    "lalowi1" FLOAT   NOT NULL,
    "lalowi1share" FLOAT   NOT NULL,
    "lakids1" FLOAT   NOT NULL,
    "lakids1share" FLOAT   NOT NULL,
    "laseniors1" FLOAT   NOT NULL,
    "laseniors1share" FLOAT   NOT NULL,
    "lawhite1" FLOAT   NOT NULL,
    "lawhite1share" FLOAT   NOT NULL,
    "lablack1" FLOAT   NOT NULL,
    "lablack1share" FLOAT   NOT NULL,
    "laasian1" FLOAT   NOT NULL,
    "laasian1share" FLOAT   NOT NULL,
    "lanhopi1" FLOAT   NOT NULL,
    "lanhopi1share" FLOAT   NOT NULL,
    "laaian1" FLOAT   NOT NULL,
    "laaian1share" FLOAT   NOT NULL,
    "laomultir1" FLOAT   NOT NULL,
    "laomultir1share" FLOAT   NOT NULL,
    "lahisp1" FLOAT   NOT NULL,
    "lahisp1share" FLOAT   NOT NULL,
    "lahunv" FLOAT   NOT NULL,
    "lahunv1share" FLOAT   NOT NULL,
    "lasnap1" FLOAT   NOT NULL,
    "lasnap1share" FLOAT   NOT NULL,
    "lapop10" FLOAT   NOT NULL,
    "lapop10share" FLOAT   NOT NULL,
    "lalowi10" FLOAT   NOT NULL,
    "lalowi10share" FLOAT   NOT NULL,
    "lakids10" FLOAT   NOT NULL,
    "lakids10share" FLOAT   NOT NULL,
    "laseniors10" FLOAT   NOT NULL,
    "laseniors10share" FLOAT   NOT NULL,
    "lawhite10" FLOAT   NOT NULL,
    "lawhite10share" FLOAT   NOT NULL,
    "lablack10" FLOAT   NOT NULL,
    "lablack10share" FLOAT   NOT NULL,
    "laasian10" FLOAT   NOT NULL,
    "laasian10share" FLOAT   NOT NULL,
    "lanhopi10" FLOAT   NOT NULL,
    "lanhopi10share" FLOAT   NOT NULL,
    "laaian10" FLOAT   NOT NULL,
    "laaian10share" FLOAT   NOT NULL,
    "laomultir10" FLOAT   NOT NULL,
    "laomultir10share" FLOAT   NOT NULL,
    "lahisp10" FLOAT   NOT NULL,
    "lahisp10share" FLOAT   NOT NULL,
    "lahunv10" FLOAT   NOT NULL,
    "lahunv10share" FLOAT   NOT NULL,
    "lasnap10" FLOAT   NOT NULL,
    "lasnap10share" FLOAT   NOT NULL,
    "lapop20" FLOAT   NOT NULL,
    "lapop20share" FLOAT   NOT NULL,
    "lalowi20" FLOAT   NOT NULL,
    "lalowi20share" FLOAT   NOT NULL,
    "lakids20" FLOAT   NOT NULL,
    "lakids20share" FLOAT   NOT NULL,
    "laseniors20" FLOAT   NOT NULL,
    "laseniors20share" FLOAT   NOT NULL,
    "lawhite20" FLOAT   NOT NULL,
    "lawhite20share" FLOAT   NOT NULL,
    "lablack20" FLOAT   NOT NULL,
    "lablack20share" FLOAT   NOT NULL,
    "laasian20" FLOAT   NOT NULL,
    "laasian20share" FLOAT   NOT NULL,
    "lanhopi20" FLOAT   NOT NULL,
    "lanhopi20share" FLOAT   NOT NULL,
    "laaian20" FLOAT   NOT NULL,
    "laaian20share" FLOAT   NOT NULL,
    "laomultir20" FLOAT   NOT NULL,
    "laomultir20share" FLOAT   NOT NULL,
    "lahisp20" FLOAT   NOT NULL,
    "lahisp20share" FLOAT   NOT NULL,
    "lahunv20" FLOAT   NOT NULL,
    "lahunv20share" FLOAT   NOT NULL,
    "lasnap20" FLOAT   NOT NULL,
    "lasnap20share" FLOAT   NOT NULL,
    "TractLOWI" INT   NOT NULL,
    "TractKids" INT   NOT NULL,
    "TractSeniors" INT   NOT NULL,
    "TractWhite" INT   NOT NULL,
    "TractBlack" INT   NOT NULL,
    "TractAsian" INT   NOT NULL,
    "TractNHOPI" INT   NOT NULL,
    "TractAIAN" INT   NOT NULL,
    "TractOMultir" INT   NOT NULL,
    "TractHispanic" INT   NOT NULL,
    "TractHUNV" INT   NOT NULL,
    "TractSNAP" INT   NOT NULL
);

CREATE TABLE "2015_Totals" (
    "CensusTract" FLOAT,
    "State" VARCHAR,
    "County" VARCHAR,
    "TractLOWI" INT,
    "TractKids" INT,
    "TractSeniors" INT,
    "TractWhite" INT,
    "TractBlack" INT,
    "TractAsian" INT,
    "TractNHOPI" INT,
    "TractAIAN" INT,
    "TractOMultir" INT,
    "TractHispanic" INT,
    "TractHUNV" INT,
    "TractSNAP" INT
);

CREATE TABLE "2019_census" (
    "CensusTract" FLOAT,
    "State" VARCHAR,
    "County" VARCHAR,
    "Urban" BOOL,
    "POP2010" INT,
    "OHU2010" INT,
    "GroupQuartersFlag" BOOL,
    "NUMGQTRS" INT,
    "PCTGQTRS" FLOAT,
    "LILATracts_1And10" BOOL,
    "LILATracts_halfAnd10" BOOL,
    "LILATracts_1And20" BOOL,
    "LILATracts_Vehicle" BOOL,
    "HUNVFlag" BOOL,
    "LowIncomeTracts" BOOL,
    "PovertyRate" FLOAT,
    "MedianFamilyIncome" INT,
    "LA1and10" BOOL,
    "LAhalfand10" BOOL,
    "LA1and20" BOOL,
    "LATracts_half" BOOL,
    "LATracts1" BOOL,
    "LATracts10" BOOL,
    "LATracts20" BOOL,
    "LATractsVehicle_20" BOOL,
    "LAPOP1_10" FLOAT,
    "LAPOP05_10" FLOAT,
    "LAPOP1_20" FLOAT,
    "LALOWI1_10" FLOAT,
    "LALOWI05_10" FLOAT,
    "LALOWI1_20" FLOAT,
    "lapophalf" FLOAT,
    "lapophalfshare" FLOAT,
    "lalowihalf" FLOAT,
    "lalowihalfshare" FLOAT,
    "lakidshalf" FLOAT,
    "lakidshalfshare" FLOAT,
    "laseniorshalf" FLOAT,
    "laseniorshalfshare" FLOAT,
    "lawhitehalf" FLOAT,
    "lawhitehalfshare" FLOAT,
    "lablackhalf" FLOAT,
    "lablackhalfshare" FLOAT,
    "laasianhalf" FLOAT,
    "laasianhalfshare" FLOAT,
    "lanhopihalf" FLOAT,
    "lanhopihalfshare" FLOAT,
    "laaianhalf" FLOAT,
    "laaianhalfshare" FLOAT,
    "laomultirhalf" FLOAT,
    "laomultirhalfshare" FLOAT,
    "lahisphalf" FLOAT,
    "lahisphalfshare" FLOAT,
    "lahunvhalf" FLOAT,
    "lahunvhalfshare" FLOAT,
    "lasnaphalf" FLOAT,
    "lasnaphalfshare" FLOAT,
    "lapop1" FLOAT,
    "lapop1share" FLOAT,
    "lalowi1" FLOAT,
    "lalowi1share" FLOAT,
    "lakids1" FLOAT,
    "lakids1share" FLOAT,
    "laseniors1" FLOAT,
    "laseniors1share" FLOAT,
    "lawhite1" FLOAT,
    "lawhite1share" FLOAT,
    "lablack1" FLOAT,
    "lablack1share" FLOAT,
    "laasian1" FLOAT,
    "laasian1share" FLOAT,
    "lanhopi1" FLOAT,
    "lanhopi1share" FLOAT,
    "laaian1" FLOAT,
    "laaian1share" FLOAT,
    "laomultir1" FLOAT,
    "laomultir1share" FLOAT,
    "lahisp1" FLOAT,
    "lahisp1share" FLOAT,
    "lahunv" FLOAT,
    "lahunv1share" FLOAT,
    "lasnap1" FLOAT,
    "lasnap1share" FLOAT,
    "lapop10" FLOAT,
    "lapop10share" FLOAT,
    "lalowi10" FLOAT,
    "lalowi10share" FLOAT,
    "lakids10" FLOAT,
    "lakids10share" FLOAT,
    "laseniors10" FLOAT,
    "laseniors10share" FLOAT,
    "lawhite10" FLOAT,
    "lawhite10share" FLOAT,
    "lablack10" FLOAT,
    "lablack10share" FLOAT,
    "laasian10" FLOAT,
    "laasian10share" FLOAT,
    "lanhopi10" FLOAT,
    "lanhopi10share" FLOAT,
    "laaian10" FLOAT,
    "laaian10share" FLOAT,
    "laomultir10" FLOAT,
    "laomultir10share" FLOAT,
    "lahisp10" FLOAT,
    "lahisp10share" FLOAT,
    "lahunv10" FLOAT,
    "lahunv10share" FLOAT,
    "lasnap10" FLOAT,
    "lasnap10share" FLOAT,
    "lapop20" FLOAT,
    "lapop20share" FLOAT,
    "lalowi20" FLOAT,
    "lalowi20share" FLOAT,
    "lakids20" FLOAT,
    "lakids20share" FLOAT,
    "laseniors20" FLOAT,
    "laseniors20share" FLOAT,
    "lawhite20" FLOAT,
    "lawhite20share" FLOAT,
    "lablack20" FLOAT,
    "lablack20share" FLOAT,
    "laasian20" FLOAT,
    "laasian20share" FLOAT,
    "lanhopi20" FLOAT,
    "lanhopi20share" FLOAT,
    "laaian20" FLOAT,
    "laaian20share" FLOAT,
    "laomultir20" FLOAT,
    "laomultir20share" FLOAT,
    "lahisp20" FLOAT,
    "lahisp20share" FLOAT,
    "lahunv20" FLOAT,
    "lahunv20share" FLOAT,
    "lasnap20" FLOAT,
    "lasnap20share" FLOAT,
    "TractLOWI" INT,
    "TractKids" INT,
    "TractSeniors" INT,
    "TractWhite" INT,
    "TractBlack" INT,
    "TractAsian" INT,
    "TractNHOPI" INT,
    "TractAIAN" INT,
    "TractOMultir" INT,
    "TractHispanic" INT,
    "TractHUNV" INT,
    "TractSNAP" INT   
);

CREATE TABLE "2019_Totals" (
    "CensusTract" FLOAT,
    "State" VARCHAR,
    "County" VARCHAR,
    "TractLOWI" FLOAT,
    "TractKids" FLOAT,
    "TractSeniors" FLOAT,
    "TractWhite" FLOAT,
    "TractBlack" FLOAT,
    "TractAsian" FLOAT,
    "TractNHOPI" FLOAT,
    "TractAIAN" FLOAT,
    "TractOMultir" FLOAT,
    "TractHispanic" FLOAT,
    "TractHUNV" FLOAT,
    "TractSNAP" FLOAT
);



